baseURL : ''
languageCode : 'en-us'
title : 'Pinggy' 

markup:
  goldmark:
    renderer:
      unsafe: true

menus: 
  main:
  - name: Home
    url: "/"
    weight: 90
  - name: Pricing
    url: /#prices
    weight: 100
  - name: Docs
    url: /docs
    weight: 110
  - name: Contact Us
    url: /contact_us
    weight: 120

  # - name: Terms of Service
  #   url: /Terms_of_Service
  #   weight: 110
  # - name: Cancellation and Return Policy
  #   url: /Return_policy
  #   weight: 120